### ISSUE TITLE
The CLI crashes sometimes while searching for instances with tags

### ISSUE THREAD

**Issue by prashantkalkar** [prashantkalkar/ec2-cli#6]
The CLI seems to crash with following error while searching using tags.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e8af68]

goroutine 1 [running]:
github.com/prashantkalkar/ec2-cli/ec2cli.AWSClientImpl.GetAllInstances.func1({0xc000358ba8, {0xc000358d50, 0x6}, {0x294e190, 0x0, 0x0}, {0x0, 0x0}, 0x0, 0xc000366540, ...})
	/Users/prashantkalkar/ec2-cli/ec2cli/aws_client_impl.go:58 +0x8
github.com/prashantkalkar/ec2-cli/ec2cli.AWSClientImpl.ec2ResultToInstanceResult({{0x235c9c0?, 0xc0001ec6e0?}, 0x10?}, 0x219c358, {0x2143529, 0x4}, 0xc0001aedc0?)
	/Users/prashantkalkar/ec2-cli/ec2cli/aws_client_impl.go:33 +0x322
github.com/prashantkalkar/ec2-cli/ec2cli.AWSClientImpl.GetAllInstances({{0x235c9c0?, 0xc0001ec6e0?}, 0x0?}, {0x2143529, 0x4})
	/Users/prashantkalkar/ec2-cli/ec2cli/aws_client_impl.go:58 +0xff
github.com/prashantkalkar/ec2-cli/ec2cli.findInstancesForNonEmptySearchTags({0xc0001ce920, 0x2, 0x0?}, {0x2373d50?, 0xc0001a0318?})
	/Users/prashantkalkar/ec2-cli/ec2cli/find_ec2.go:25 +0x5e
github.com/prashantkalkar/ec2-cli/ec2cli.FindEC2InstancesByTagValues(...)
	/Users/prashantkalkar/ec2-cli/ec2cli/find_ec2.go:17
github.com/prashantkalkar/ec2-cli/ec2cli.PrintInstancesByTags(0x0?, {0xc0001ce920?, 0x2?, 0x2?}, 0x1?)
	/Users/prashantkalkar/ec2-cli/ec2cli/print-instances-by-tags.go:7 +0x9b
main.main.func1(0xc00022fb80?, {0xc000246480?, 0x3?, 0x3?})
	/Users/prashantkalkar/ec2-cli/main.go:25 +0x52
github.com/spf13/cobra.(*Command).execute(0xc00022fb80, {0xc0001ae010, 0x3, 0x3})
	/Users/prashantkalkar/sdk/go1.17.2/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc00022fb80)
	/Users/prashantkalkar/sdk/go1.17.2/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/prashantkalkar/sdk/go1.17.2/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/Users/prashantkalkar/ec2-cli/main.go:38 +0x2f6
```

**Comment by prashantkalkar** [comment]
This seems to happen during parsing of instances which are terminated.

**Comment by prashantkalkar** [comment]
It seems to be failing when the instance has null primary IP address

```
{
...
"PrivateIpAddress": null,
...
}
```
Which will be the case for terminated instances.

**Comment by prashantkalkar** [comment]
Fixed by https://github.com/prashantkalkar/ec2-cli/pull/7
